# Generated by Django 3.2.5 on 2021-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
         migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True,null=True, default='no-product-image.png', upload_to='images/'),
        ),
    ]
