# Generated by Django 3.2.5 on 2021-07-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
