# Generated by Django 3.2.5 on 2021-09-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_img'),
        ('store', '0011_alter_product_product_img'),
    ]

    operations = [
    ]
